version: "3.8"

services:
  candy-fight-database:
    image: mongo:bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: candy-fight
      MONGO_INITDB_ROOT_PASSWORD: candy-fight
    ports:
    - 27017:27017
    volumes:
    - candy-fight-mongo-data:/data/db

volumes:
  candy-fight-mongo-data:
