name: candy-fight api - ci

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

env:
  CI: true
  TZ: Europe/Paris
  GO_VERSION: 1.16.4

jobs:
  lint:
    services:
      mongodb:
        image: mongo:bionic
        env:
          MONGO_INITDB_ROOT_USERNAME: candy-fight
          MONGO_INITDB_ROOT_PASSWORD: candy-fight
        ports:
          - 27017:27017
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: setup go env
        run: |
          export PATH=$PATH:`go env GOPATH`/bin && \
          go get -u github.com/swaggo/swag/cmd/swag && \
          go get -u honnef.co/go/tools/cmd/staticcheck

      - name: lint code
        run: |
          swag init --parseDependency
          gofmt -s -w **/*.go
          staticcheck ./...

      - name: run tests
        run: |
          go test ./...
